# Generated by Django 6.0.5 on 2026-05-11 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomURLRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('whitelist', 'Whitelist'), ('blacklist', 'Blacklist')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de URL Personalizada',
                'verbose_name_plural': 'Regras de URL Personalizadas',
                'unique_together': {('user', 'url_pattern')},
            },
        ),
    ]
