# Generated by Django 6.0.5 on 2026-06-04 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customurlrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultBlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('adult', 'Conteúdo Adulto'), ('social_media', 'Redes Sociais'), ('malware', 'Malware'), ('fakenews', 'Fake News'), ('gambling', 'Jogos de Azar')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lista de Bloqueio Padrão',
                'verbose_name_plural': 'Listas de Bloqueio Padrão',
            },
        ),
        migrations.CreateModel(
            name='DefaultBlockListDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='accounts.defaultblocklist')),
            ],
            options={
                'verbose_name': 'Domínio da Lista Padrão',
                'verbose_name_plural': 'Domínios das Listas Padrão',
                'unique_together': {('block_list', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='UserBlockListActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='accounts.defaultblocklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated_block_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ativação de Lista Padrão',
                'verbose_name_plural': 'Ativações de Listas Padrão',
                'unique_together': {('user', 'block_list')},
            },
        ),
    ]
