# Generated by Django 6.0.4 on 2026-06-07 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_default_block_lists'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048, verbose_name='URL Bloqueada')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('block_source', models.CharField(choices=[('USER', 'Usuário'), ('GROUP', 'Grupo')], default='USER', max_length=10, verbose_name='Origem do Bloqueio')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_accesses', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acesso Bloqueado',
                'verbose_name_plural': 'Acessos Bloqueados',
                'ordering': ['-timestamp'],
            },
        ),
    ]
