# Generated by Django 6.0.5 on 2026-06-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blockedaccess'),
        ('accounts', '0004_family_groups'),
    ]

    operations = [
    ]
